version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:14.15

jobs:
  checkout:
    executor: node
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  npm_install:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Installing npm dependencies
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: npm run lint

  typecheck:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Static type check
          command: npm run typecheck

  test:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm run test
